config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root       'dashboard#show'
  resources  :friendships, only: [:create, :update, :destroy]
  get "/users/search" => "searches#show", :as => "search"
  resources  :users
  resources  :posts do
    member do
      put "like", to: "likes#create"
      put "dislike", to: "likes#destroy"
    end
  end
  get        'requests' => 'friendships#index', as: :requests
  resources  :comments, only: [:create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  validates :name, presence: true
  after_create :friend_default_user

  #has_attached_file :avatar, styles: { medium: "300x300>", thumb: "40x40>" }, default_url: "/images/:style/default-no-picture.jpg"
  #validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # ActiveRecord relations
  has_many :authored_posts, :class_name => "Post", :foreign_key => "author_id", dependent: :destroy

  # establish the many-to-many relationships:
  # passive friendships are those in which said user is the requested friend
  # active_friends are friends a user requested that has accepted (sent)
  # passive_friends are friends which requested the user which the user has accepted (accepted friend invite)
  # pending friends are those which a user has sent an invite to, but have not accepted (sent)
  # a received_friendship is an invitation a user has received, but yet not accepted (received)
  has_many :friendships
  has_many :passive_friendships, :class_name => "Friendship", :foreign_key => "friend_id"

  has_many :active_friends, -> { where(friendships: { accepted: true }) }, 
                            :through => :friendships, :source => :friend
  has_many :passive_friends, -> {where(friendships: { accepted: true }) },
                            :through => :passive_friendships, :source => :user
  has_many :pending_friends, -> {where(friendships: { accepted: false }) },
                            :through => :friendships, :source => :friend
  has_many :received_friends, -> { where(friendships: { accepted: false}) },
                              :through => :passive_friendships, :source => :user
  has_many :likes
  has_many :liked_posts, :through => :likes, :source => :post
  has_many :comments, :foreign_key => "author_id"
  has_many :commented_posts, :through => :comments, :source => :post

  def mutual_friends
    active_friends | passive_friends
  end

  # user.accept_friend(friendship) will update accepted: to true
  def accept_friend(friendship)
    friendship.update_attributes(accepted: true)
  end

  # will return the friendship object by passing in the friend object
  def friendship(friend)
    Friendship.find_by(user_id: self, friend_id: friend) || Friendship.find_by(friend_id: self, user_id: friend)
  end

  def mutual_friend?(friend)
    mutual_friends.include?(friend)
  end

  def friend_count
    mutual_friends.count
  end

  def received_friends_count
    received_friends.count if received_friends.any?
  end

  def role
    "user"
  end
  
  def like(post)
    like = likes.build(:post => post)
    like.save
  end

  def unlike(post)
    like = likes.find_by(post: post)
    like.destroy
  end

  def like?(post)
    likes.where(post: post).any?
  end

  private
    def friend_default_user
      if self.id != 1
        Friendship.create!(user_id: self.id,friend_id: 1, accepted: true)
      end
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_login
	def show
    @post = Post.new
    @comment = Comment.new
		@user = User.find(params[:id])
	end

  def index
    users = User.paginate(:page => params[:page])
    render "users/_users", locals: {users: users}
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<tr>
  <td><%= image_tag(user.avatar.thumb.url, size: "40x40", class: "user-img-index")%><%= link_to "#{user.name}", user %></td>
  <td><%= user.email %></td>
</tr>

app/views/users/_users.html.erb
<div class="panel panel-primary users-index">
  <div class="panel-heading fb-blue">Users</div>
  <div class="panel-body">
  	<%= form_for(:search, url: search_path, method: :get) do |f| %>
			<%= f.text_field :term %>
			<%= f.submit "Search" %>
		<% end %>
  </div>
  <div class="fill" >
  <table class="table table-striped">
    <thead>
      <tr>
        <th>User</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
    <% users.each do |user| %>
    	<%= render partial:"users/user", locals: { user: user } %>
    <% end %>
    </tbody>
  </table>
    <div class="panel-footer">
      <%= "Page #{users.current_page} of #{users.total_pages}" %><br>
      <%= will_paginate users%>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render "users/users", locals: { users: @users } %>

app/views/users/show.html.erb
<div class="row profile-head">
	<div class="col-md-10 col-md-offset-2 user-info">
		<div class="profile-overview">
			<%= image_tag(@user.avatar.url, width:"200", height: "200", class:"user-pic") %>
	  	<div class="user-details">
	      <div class="user-name">
	      	<%= @user.name %>
	      	<div class="friend-command"><%= friend_link(@user) %></div>
	      </div>
	      <span class="bio">
	      </span>
	   	</div>
   	</div>
	</div>
</div>

<div class="row">
	<div class="col-md-2 col-md-offset-2 friends-col">
		<div class="friend-header">Friends (<%= @user.friend_count%>)</div>
    <div class="friends">
    	<%= friends_list(@user) %>
      <% if @user.mutual_friends.count > 5 %>
	      <a href="#">View More</a>
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
		<div class="user-feed">
			<% if current_user == @user %>
				<%= render 'posts/form' %>
			<% end %>
			<div id="posts"%>
				<%= render @user.authored_posts.order('id DESC') %>
			</div>
		</div>
	</div>
</div>