config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root       'dashboard#show'
  resources  :friendships, only: [:create, :update, :destroy]
  get "/users/search" => "searches#show", :as => "search"
  resources  :users
  resources  :posts do
    member do
      put "like", to: "likes#create"
      put "dislike", to: "likes#destroy"
    end
  end
  get        'requests' => 'friendships#index', as: :requests
  resources  :comments, only: [:create, :destroy]
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :author, :class_name => "User"
  has_many :likes
  has_many :comments
  validates :author, presence: true 
  validates :content, presence: true, :unless => :picture?
  validate :picture_size
  
  def likes_count
    ActionController::Base.helpers.pluralize(likes.count, 'Like')
  end

  def comments_count
    ActionController::Base.helpers.pluralize(comments.count, 'Comment')
  end

  private

    # Validate the size of an uploaded picture
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login
  respond_to :html, :js, :json

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    if remotipart_submitted?
      render :layout => false, :template => ('posts/create.js.erb'), :status => (@post.errors.any? ? :unprocessable_entity : :ok)
    else
      respond_with(@post)
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_with(@post)
  end

  private

    def post_params
      params.require(:post).permit(:author_id, :content, :picture, :picture_cache)
    end
end

app/helpers/posts_helper.rb
module PostsHelper

  def comments_for(post)
    if show_all_comments?(post)
      render post.comments
    else
      render post.comments.last(2)
    end
  end

  def post_admin_commands(post)
    if post.author == current_user
      link_to "X", post_path(post), remote: true, class: 'delete-post pull-right', :method => :delete, 
      data: {confirm: "Are you sure?"}, title: "Delete post"
    end
  end

  private
    def view_more(post)
      if post.comments.size > 2 && ! show_all_comments?(post)
        render "comments/view_more", post: post
      end
    end

    def show_all_comments?(post)
      params[:post_id].to_i == post.id
    end
end

app/views/posts/_comment_form.html.erb
<div class="comment-box">
  <div class="comment-form">
 <%= form_for :comment, :url => {:controller => "comments", :action => "create"}, remote: true, :html => {:class => 'form-inline', :id => 'comment-form' } do |f| %>
  	<div class="form-group">
  	<%= image_tag(current_user.avatar.url(:thumb), size: "32x32") %>
  		<%= f.text_area(:content, class: 'form-control comment-input', id: "post_#{post.id}_comment",cols: 50, rows: 1, placeholder: 'Write something...') %>
  		<%= f.hidden_field :post_id, :value => post.id %>
  		<%= f.hidden_field :author_id, :value => current_user.id %>
  		<%= f.submit "Post", class: "btn btn-primary comment-submit" %>
  	</div>
  <% end %>
   
  </div>
</div>

app/views/posts/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body create-post">
    <div class="post-header">
    <%= form_for Post.new, :url => {:controller => "posts", :action => "create"}, remote: true, multipart: true, authenticity_token: true, :html => {:class => 'form-horizontal', :id => 'post-form' } do |f| %>
    	<div class="post-status">
        <img src="http://i.imgur.com/FR9IOEw.png"> <!-- compose icon -->
        <span class="status-select">Status</span>
        <%= image_tag("add_photo_icon.png") %>
        <form id="post-form">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', value: "Add Photo" %>
        <span class="file_name"></span>
        <%= f.hidden_field :picture_cache %>
      </div>
      <span class="triangle-select"></span>
    </div>
    
			<%= f.text_area :content, class: 'form-control post-input', :placeholder => "Write something..." %>
		<%= f.hidden_field :author_id, :value => current_user.id %>
    <div class="post-footer">
    <%= hidden_field_tag(:location, @location) %>
		<%= f.submit "Post", class: "btn btn-sm btn-primary post-submit" %>
		<% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('#post_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/posts/_like_commands_liked.html.erb
<%= link_to dislike_post_path(post), remote: true, class: 'like-post', :method => :put, 
		data: { toggle_href: like_post_path(post), id: post.id } do %>
	<div class="like-commands liked">
		<span class="glyphicon glyphicon-thumbs-up like"></span>
		<div class="command-text like-text">Like</div>
	</div>
<% end %>

app/views/posts/_like_commands_unliked.html.erb
<%= link_to like_post_path(post), remote: true, class: 'like-post', :method => :put,
		data: { toggle_href: dislike_post_path(post), id: post.id } do %>
	<div class="like-commands">
		<span class="glyphicon glyphicon-thumbs-up like"></span>
		<div class="command-text like-text">Like</div>
	</div>
<% end %>

app/views/posts/_post.html.erb
<%= div_for post do |post| %>
	<%= render partial:"posts/post_header", locals: {post: post }%>
	<div class="panel panel-default comments">
	  <div class="panel-body">
	  	<%= view_more(post) %>
	  	<div class="comments-list">
				<%= comments_for(post) %>
			</div>
	    <%= render partial:"posts/comment_form", locals: { post: post } %>
	  </div>
	</div>
<% end %>

app/views/posts/_post_header.html.erb
	<div class="panel panel-default extended" id="post-<%= post.id %>">
	  
	  <div class="panel-body head">
	    <%= image_tag(post.author.avatar.thumb.url, size: "40x40")%>

	    <%= link_to post.author.name, post.author, :class => "author-link" %>
	    <div class="post-admin">
	     	<%= post_admin_commands(post) %>
   	  </div>
	    <div class="time-posted"><%= time_ago_in_words(post.updated_at) %></div>
	  </div>
	  
	  <div class="panel-body content">
	  	<%= h(post.content).gsub(/\n/, '<br/>').html_safe %>
	  	<div class="post-picture"><%= image_tag post.picture.url if post.picture? %></div>
	  </div>
	  <div class="post-info">
	    <div class="like-count" data-id="<%= post.id %>"><%= pluralize(post.likes.count, 'Like') %></div>
	    <div class="comment-count" data-id="<%= post.id%>"><%= pluralize(post.comments.count, 'Comment') %></div>
	  </div>
	  <hr>
    <div class="post-commands">
    	<%= post_like_commands(current_user, post) %>
    	<a href="#post_<%= post.id %>">
      	<span class="glyphicon glyphicon-comment comment-action"></span>
      	<div class="command-text comment-text">Comment</div>
    	</a>
  	</div>
	</div>

app/views/posts/create.js.erb
<%= remotipart_response do %>
  <% unless @post.errors.any? %>
   $("#posts").prepend("<%= j render partial: 'post', locals: {post: @post} %>");
		$('#post_<%= "#{@post.id}" %>').hide().fadeIn('slow');
		$('#post-form')[0].reset();
		$("#error-div").fadeOut("slow");

		$('input:file').change(function() {
		  var fileName, path;
		  path = $(this).val();
		  fileName = path.replace(/^.*\\/, "");
		  $(".file_name").text(fileName);
		});

  <% else %>
	  $("#error-div").hide();
		$("#error-div").html('<%= j render :partial => 'shared/error_messages', locals: {object: @post}  %>');
		$("#error-div").fadeIn("slow");
  <% end %>
<% end %>

$(".file_name").text("")

app/views/posts/destroy.js.erb
$("#post_<%= @post.id %>").fadeOut();