config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root       'dashboard#show'
  resources  :friendships, only: [:create, :update, :destroy]
  get "/users/search" => "searches#show", :as => "search"
  resources  :users
  resources  :posts do
    member do
      put "like", to: "likes#create"
      put "dislike", to: "likes#destroy"
    end
  end
  get        'requests' => 'friendships#index', as: :requests
  resources  :comments, only: [:create, :destroy]
end

app/views/layouts/_friend_request_nav.html.erb
<li class="hz">
	<%= link_to "#{rec_friend.name}", rec_friend %>
	<%= link_to "Accept", friendship_path(id: rec_friend), :method => "put", class: "btn btn-success" %>
	<%= link_to "Remove", friendship_path(current_user.friendship(rec_friend)), :method => "delete", class: "btn btn-danger"%>
</li>
<% unless rec_friend == current_user.received_friends.last %>
	<li class="divider"></li>
<% end %>

app/views/layouts/_guest_nav.html.erb
<li><%= link_to 'Sign Up', new_user_registration_path %></li>
<li><%= link_to 'Login', new_user_session_path %></li>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
	<div class="container">
		<div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
			<%= link_to "railsbook", root_path, class: "navbar-brand", data: { no_turbolink: true } %>
		</div>
		<div class="navbar-collapse collapse" id="myNavbar">
			<ul class="nav navbar-nav navbar-right">
				<%= render "layouts/#{current_user.role}_nav" %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/_user_nav.html.erb
<li>
	<%= link_to current_user do %>
		<span class="usr-img"><%= image_tag(current_user.avatar.url(:thumb), size: "20x20") %>
		</span>
		<%= current_user.name %>
	<% end %>
</li>

<li><%= link_to 'Home', root_path, id: "home-link", data: { no_turbolink: true } %></li>
<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" id="notification-dropdown">
		<div class="number-notify"><%= current_user.received_friends_count %></div>
		<b class="glyphicon glyphicon-globe" id="notificationIcon"></b>
	</a>

	<ul class="dropdown-menu">
		<%= friend_request_nav %>
	</ul>
</li>

<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b></a>
	<ul class="dropdown-menu">
	<li><%= link_to 'Users', users_path %></li>
	<li><%= link_to 'Settings', edit_user_registration_path %></li>
	<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
	</ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Railsbook</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <!-- Favicons -->
	  <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
	  <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
	  <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
	  <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
	  <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
	  <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
	  <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
	  <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
	  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
	  <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
	  <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
	  <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
	  <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
	  <link rel="manifest" href="/manifest.json">
	  <meta name="msapplication-TileColor" content="#da532c">
	  <meta name="msapplication-TileImage" content="/mstile-144x144.png">
	  <meta name="theme-color" content="#ffffff">
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |message_type, message| %>
		    <div class="alert alert-<%= message_type %>"><%= message %></div>
		  <% end %>
		  <div id="error-div"></div>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>